/**
 * Enum of ArithmeticToken Types
 * @typedef TokenType
 * @enum {string}
 */

const TOKEN_TYPE = {
  ADDITION: "ADDITION",
  SUBTRACTION: "SUBTRACTION",
  MULTIPLICATION: "MULTIPLICATION",
  DIVISION: "DIVISION",
  LEFT_PARENTHESIS : "LEFT_PARENTHESIS",
  RIGHT_PARENTHESIS: "RIGHT_PARENTHESIS",
  VALUE: "VALUE"
};

export default TOKEN_TYPE;
